import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import MuiThemeProvider from "./components/MuiThemeProvider";
import Header from "./components/Header/Header";
import Layout from "./components/Layout/Layout";
import Footer from "./components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Data Dashboard",
  description: "Generated by Alan Hernandez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MuiThemeProvider>
          <Providers>
            <Box
              sx={{
                minHeight: "100vh",
                display: "flex",
                flexDirection: "column",
              }}
            >
              <Header />
              <Box sx={{ flex: 1, display: "flex" }}>
                <Layout>{children}</Layout>
              </Box>
              <Footer />
            </Box>

            <CssBaseline />
          </Providers>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
